// Official DepEd SSHS track and cluster data
const tracks = [
  {
    id: "academic",
    icon: '<span class="iconify" data-icon="iconsax:book-open" data-inline="false"></span>',
    title: "Academic Track",
    desc: "If you're thinking about going to college, this is the track for you. It's all about preparing you for university-level study through in-depth academic subjects.",
    accent: "#003087",
    tagbg: "rgba(0, 48, 135, 0.12)",
    tag: "College Preparatory",
    note: "Under the Strengthened SHS Program, Academic Track students take 6 Core Subjects plus electives from their chosen cluster.",
    clusters: [
      {
        name: "STEM",
        full: "Science, Technology, Engineering, and Mathematics",
         icon: '<span class="iconify" data-icon="iconsax:microscope" data-inline="false"></span>',
        desc: "If you love figuring out how things work — whether that's a chemical reaction, a computer program, or a bridge — STEM is built for you. It's challenging, but it opens doors to some of the most in-demand careers in the world.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
            { icon: '<span class="iconify" data-icon="iconsax:telescope" data-inline="false"></span>', label: "Your STEM Electives", title: "What Makes STEM Different", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "On top of the core subjects, STEM students take specialized electives: Biology 1 and 2, Chemistry 1 and 2, Physics 1 and 2, Earth and Space Science 1 and 2, and Finite Mathematics 1 and 2. These go much deeper than what you covered in Junior High.", tags: ["Biology 1 and 2", "Chemistry 1 and 2", "Physics 1 and 2", "Earth and Space Science 1 and 2", "Finite Mathematics 1 and 2"] },
            { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What STEM Will Build in You", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "You'll get really good at breaking problems down, thinking logically, reading and interpreting data, and working in a lab setting. You'll also learn how to write about science and research in a clear, structured way.", tags: ["Logical Thinking", "Data Analysis", "Lab Work", "Scientific Writing", "Problem Solving", "Research Skills"] },
            { icon: '<span class="iconify" data-icon="iconsax:school" data-inline="false"></span>', label: "College After STEM", title: "Where STEM Graduates Usually Go", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "STEM is one of the most flexible college prep clusters. Graduates commonly pursue BS Engineering, BS Computer Science, BS Nursing, BS Biology, BS Architecture, BS Medicine (pre-med), or BS Environmental Science.", tags: ["BS Engineering", "BS Computer Science", "BS Nursing", "BS Biology", "BS Architecture", "Doctor of Medicine", "BS Environmental Science"] },
            { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "STEM leads to careers that are both high-demand and well-paying. Think Engineer, Doctor, Nurse, Programmer, Software Developer, Data Analyst, Scientist, Architect, and many more.", tags: ["Engineer", "Doctor", "Nurse", "Programmer", "Data Analyst", "Scientist", "Architect"] }
        ]
      },
      {
        name: "Business and Entrepreneurship",
        full: "Business, Accountancy, and Entrepreneurship",
        icon: '<span class="iconify" data-icon="iconsax:chart-bar" data-inline="false"></span>',
        desc: "If you've ever had a business idea, or if you just really like understanding how money and organizations work, this cluster is a natural fit. It teaches you how businesses run from the inside out.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:briefcase" data-inline="false"></span>', label: "Your Business Cluster Electives", title: "What You'll Study in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Your electives will include Business 1 (Basic Accounting), Business 2 (Business Finance and Income Taxation), Business 3 (Business Economics), Contemporary Marketing, Entrepreneurship, and Introduction to Organization and Management.", tags: ["Basic Accounting", "Business Finance and Taxation", "Business Economics", "Contemporary Marketing", "Entrepreneurship", "Organization and Management"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll learn how to manage money, read financial reports, plan a business, and think like a business owner or manager. Communication and leadership skills are a big part of this too.", tags: ["Financial Literacy", "Business Planning", "Leadership", "Marketing", "Decision Making", "Entrepreneurial Thinking"] },
          { icon: '<span class="iconify" data-icon="iconsax:school" data-inline="false"></span>', label: "College After This Cluster", title: "Where Business Graduates Usually Go", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "This cluster prepares you well for BS Accountancy, BS Business Administration, BS Financial Management, BS Marketing Management, BS Entrepreneurship, or BS Economics.", tags: ["BS Accountancy", "BS Business Administration", "BS Financial Management", "BS Marketing Management", "BS Entrepreneurship", "BS Economics"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Graduates from this cluster often become Accountants, Business Owners, Financial Analysts, Marketing Managers, Bank Officers, HR Managers, or Company Executives.", tags: ["Accountant", "Business Owner", "Financial Analyst", "Marketing Manager", "Bank Officer", "HR Manager"] }
        ]
      },
      {
        name: "Arts, Social Science, and Humanities",
        full: "Humanities, Social Sciences, and Creative Arts",
        icon: '<span class="iconify" data-icon="iconsax:earth" data-inline="false"></span>',
        desc: "If you're the type who loves debating ideas, understanding people, writing, or creating things — this cluster is for you. It's broad, creative, and deeply human.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:pencil" data-inline="false"></span>', label: "Your Cluster Electives", title: "What You'll Study in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Electives include Arts 1 (Visual, Literary, Media, Applied, and Traditional Arts), Arts 2 (Music, Dance, and Theater), Creative Composition, Contemporary Literature, Introduction to Philosophy, Philippine Governance, Social Sciences Theory and Practice, and more.", tags: ["Arts 1 and 2", "Creative Composition", "Contemporary Literature", "Introduction to Philosophy", "Philippine Governance and Politics", "Social Sciences"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll grow your ability to write well, speak confidently, think critically about society and culture, and understand human behavior. Research and creative expression are central to this cluster.", tags: ["Writing and Composition", "Public Speaking", "Critical Thinking", "Research", "Cultural Awareness", "Creative Expression"] },
          { icon: '<span class="iconify" data-icon="iconsax:school" data-inline="false"></span>', label: "College After This Cluster", title: "Where Graduates Usually Go", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "This cluster opens doors to AB Communication, AB Political Science, BS Psychology, BS Social Work, AB Philosophy, BS Education, AB Journalism, and even Law.", tags: ["AB Communication", "AB Political Science", "BS Psychology", "BS Social Work", "AB Philosophy", "BS Education", "Law"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Graduates can become Teachers, Journalists, Lawyers, Psychologists, Social Workers, Artists, Diplomats, Writers, or Community Leaders.", tags: ["Teacher", "Journalist", "Lawyer", "Psychologist", "Social Worker", "Artist", "Diplomat", "Writer"] }
        ]
      },
      {
        name: "Sports, Health, and Wellness",
        full: "Sports Science, Physical Education, and Wellness",
        icon: '<span class="iconify" data-icon="iconsax:soccer" data-inline="false"></span>',
        desc: "This isn't just for athletes. It's for anyone who's interested in how the human body moves, performs, and stays healthy — whether you want to coach, train people, or become a healthcare professional.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:run" data-inline="false"></span>', label: "Your Cluster Electives", title: "What You'll Study in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Your electives include Human Movement 1 (Basic Anatomy in Sports and Exercise), Human Movement 2 (Motor Skills Development), Physical Education 1 (Fitness and Recreation), Physical Education 2 (Sports and Dance), Sports Activity Management, Sports Coaching, and Sports Officiating.", tags: ["Human Movement 1 and 2", "Physical Education 1 and 2", "Sports Activity Management", "Sports Coaching", "Sports Officiating"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll understand how the body works during physical activity, learn how to coach and manage sports events, develop discipline, and build leadership and teamwork skills that carry over into any career.", tags: ["Anatomy and Body Science", "Coaching Techniques", "Sports Management", "Leadership", "Teamwork", "Discipline"] },
          { icon: '<span class="iconify" data-icon="iconsax:school" data-inline="false"></span>', label: "College After This Cluster", title: "Where Graduates Usually Go", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "This cluster is a great preparation for BS Physical Education, BS Sports Science, BS Kinesiology, BS Health and Physical Education, or even BS Nursing and other allied health courses.", tags: ["BS Physical Education", "BS Sports Science", "BS Kinesiology", "BS Health and PE", "BS Nursing"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Graduates can become PE Teachers, Coaches, Sports Trainers, Sports Managers, Athletic Directors, Physical Therapists, or even Professional Athletes.", tags: ["PE Teacher", "Coach", "Sports Trainer", "Sports Manager", "Athletic Director", "Physical Therapist"] }
        ]
      }
    ]
  },
  {
    id: "techpro",
    icon: '<span class="iconify" data-icon="iconsax:hammer-wrench" data-inline="false"></span>',
    title: "TechPro Track",
    desc: "Not everyone's path goes through college — and that's completely okay. The TechPro Track is about learning hands-on, practical skills that the real world actually needs. You can even earn a TESDA National Certification while still in Senior High School.",
    accent: "#FFC72C",
    tagbg: "rgba(255, 199, 44, 0.12)",
    tag: "Skills-Based and Work-Ready",
    note: "TechPro students take the same 6 Core Subjects as Academic students, then choose electives from their cluster. Many TechPro electives come with TESDA National Certification (NC) opportunities.",
    clusters: [
      {
        name: "ICT Support and Computer Programming",
        full: "Information and Communications Technology",
        icon: '<span class="iconify" data-icon="iconsax:laptop" data-inline="false"></span>',
        desc: "This is for students who are drawn to computers, the internet, coding, and digital technology. You'll come out of this with skills that are genuinely in demand — in the Philippines and globally.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:keyboard" data-inline="false"></span>', label: "Your TechPro ICT Electives", title: "What You'll Learn in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Your electives include Computer Systems Servicing, Computer Programming in Java, Computer Programming in .NET, Computer Programming with Oracle Database, Contact Center Services, and Broadband Installation — all aligned with real industry standards.", tags: ["Computer Systems Servicing", "Computer Programming (Java)", "Computer Programming (.NET)", "Oracle Database", "Contact Center Services", "Broadband Installation"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll learn how to build and repair computers, write code, set up networks, and troubleshoot tech problems. These are skills you can use for a job or freelance work even before finishing college.", tags: ["Computer Hardware Repair", "Programming and Coding", "Network Setup", "Troubleshooting", "Technical Support", "Freelancing Skills"] },
          { icon: '<span class="iconify" data-icon="iconsax:medal" data-inline="false"></span>', label: "National Certification (TESDA)", title: "You Can Earn a Cert While Still in SHS", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "After completing your TechPro electives, you can take a TESDA assessment and earn a National Certificate II in Computer Systems Servicing or Computer Programming. This is a real credential that employers recognize.", tags: ["TESDA NC II", "Computer Systems Servicing", "Computer Programming Certification", "Employer-Recognized Credential"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "With this cluster, you can work as a Computer Technician, Web Developer, Programmer, IT Support Specialist, or Network Technician right after graduation — or continue to college for BS Computer Science or BS IT.", tags: ["Computer Technician", "Web Developer", "Programmer", "IT Support", "Network Technician", "BS Computer Science"] }
        ]
      },
      {
        name: "Hospitality and Tourism",
        full: "Food, Beverage, Hotel, and Tourism Services",
        icon: '<span class="iconify" data-icon="iconsax:silverware-fork-knife" data-inline="false"></span>',
        desc: "If you're drawn to cooking, hosting, traveling, or making people feel welcome, this cluster turns those interests into professional skills. It's practical, fast to apply, and always in demand.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:chef-hat" data-inline="false"></span>', label: "Your TechPro Hospitality Electives", title: "What You'll Learn in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Your electives cover Bakery Operations, Kitchen Operations, Food and Beverage Operations, Hotel Operations (Front Office Services), Hotel Operations (Housekeeping Services), Events Management Services, and Tourism Services.", tags: ["Bakery Operations", "Kitchen Operations", "Food and Beverage", "Hotel Front Office", "Hotel Housekeeping", "Events Management", "Tourism Services"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll develop professional kitchen skills, customer service, hotel operations know-how, event planning, and tourism management. You'll also learn how to handle real service situations — not just theory.", tags: ["Culinary Skills", "Customer Service", "Hotel Operations", "Event Planning", "Tourism Management", "Professional Standards"] },
          { icon: '<span class="iconify" data-icon="iconsax:medal" data-inline="false"></span>', label: "National Certification (TESDA)", title: "You Can Earn a Cert While Still in SHS", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Completing your electives qualifies you to take a TESDA NC II assessment in Cookery, Food and Beverage Services, Front Office Services, or Housekeeping — giving you a real professional credential before college.", tags: ["TESDA NC II", "Cookery", "Food and Beverage Services", "Front Office Services", "Housekeeping Certification"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "Graduates can work as Chefs, Bakers, Hotel Front Desk Staff, Restaurant Supervisors, Event Coordinators, or Tour Guides. For college, you can pursue BS Hospitality Management or BS Tourism.", tags: ["Chef", "Baker", "Hotel Staff", "Restaurant Supervisor", "Event Coordinator", "Tour Guide", "BS Hospitality Management"] }
        ]
      },
      {
        name: "Agri-Fishery Business and Food Innovation",
        full: "Agriculture, Fishery, and Food Production",
        icon: '<span class="iconify" data-icon="iconsax:grain" data-inline="false"></span>',
        desc: "This cluster is for students who are interested in where food comes from and how it's produced. It's more practical and entrepreneurial than people expect — there's a lot of room to grow your own business here.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:sprout" data-inline="false"></span>', label: "Your TechPro Agri-Fishery Electives", title: "What You'll Learn in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Electives include Agricultural Crops Production, Organic Agriculture Production, Aquaculture, Fish Capture, Poultry Production (Chicken), Ruminants Production, Swine Production, Food Processing, and Agro-Entrepreneurship.", tags: ["Agricultural Crops Production", "Organic Agriculture", "Aquaculture", "Fish Capture", "Poultry Production", "Food Processing", "Agro-Entrepreneurship"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll learn how to grow crops, raise animals, manage a fish farm, process food, and run an agricultural business. It's hands-on from day one and builds real entrepreneurial thinking.", tags: ["Crop Growing", "Animal Raising", "Fish Farming", "Food Processing", "Farm Business Management", "Entrepreneurship"] },
          { icon: '<span class="iconify" data-icon="iconsax:medal" data-inline="false"></span>', label: "National Certification (TESDA)", title: "You Can Earn a Cert While Still in SHS", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "You can take TESDA assessments for NC II in Agricultural Crops Production, Aquaculture, or Animal Production. These certifications qualify you to work in the agricultural sector right after graduation.", tags: ["TESDA NC II", "Agricultural Crops Production", "Aquaculture Certification", "Animal Production NC"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "Graduates can become Farm Managers, Agricultural Entrepreneurs, Aquaculture Technicians, Food Processors, or go to college for BS Agriculture, BS Fisheries, or BS Agribusiness.", tags: ["Farm Manager", "Agricultural Entrepreneur", "Aquaculture Technician", "Food Processor", "BS Agriculture", "BS Fisheries"] }
        ]
      },
      {
        name: "Creative Arts and Design Technology",
        full: "Animation, Illustration, and Visual Graphic Design",
        icon: '<span class="iconify" data-icon="iconsax:palette" data-inline="false"></span>',
        desc: "This is for students who think visually and love creating things — whether that's drawing characters, designing logos, or making animations. It combines artistry with practical digital skills.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:brush" data-inline="false"></span>', label: "Your TechPro Creative Electives", title: "What You'll Learn in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Your electives focus on Animation, Illustration, and Visual Graphic Design — three of the most in-demand creative skills in today's digital economy. You'll work with industry-standard tools and techniques.", tags: ["Animation", "Illustration", "Visual Graphic Design"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll develop real design and animation skills — not just theory. By the time you finish SHS, you'll have a portfolio of actual work you can show to clients, schools, or employers.", tags: ["Digital Animation", "Character Illustration", "Graphic Design", "Portfolio Building", "Visual Storytelling", "Creative Thinking"] },
          { icon: '<span class="iconify" data-icon="iconsax:medal" data-inline="false"></span>', label: "National Certification (TESDA)", title: "You Can Earn a Cert While Still in SHS", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Completing these electives can qualify you for TESDA certification in Visual Graphic Design, giving you a credential recognized by employers in the creative industry.", tags: ["TESDA Certification", "Visual Graphic Design NC", "Creative Industry Credential"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "Graduates can freelance or work full-time as Graphic Designers, Animators, Illustrators, and Content Creators — or go to college for BS Multimedia Arts, BS Fine Arts, or BS Graphic Technology.", tags: ["Graphic Designer", "Animator", "Illustrator", "Content Creator", "BS Multimedia Arts", "BS Fine Arts"] }
        ]
      },
      {
        name: "Aesthetic, Wellness, and Human Care",
        full: "Beauty Care, Caregiving, and Hairdressing",
        icon: '<span class="iconify" data-icon="iconsax:spa" data-inline="false"></span>',
        desc: "This cluster is for students who genuinely care about people — whether that means helping them look their best or taking care of those who can't fully care for themselves. It's a deeply human and rewarding path.",
        steps: [
          { icon: '<span class="iconify" data-icon="iconsax:book" data-inline="false"></span>', label: "Your Core Subjects (All Tracks)", title: "Subjects Every SHS Student Takes", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "No matter which cluster you pick, you'll take these six core subjects: Effective Communication, General Mathematics, General Science, Life and Career Skills, Philippine History and Society, and Filipino.", tags: ["Effective Communication", "General Mathematics", "General Science", "Life and Career Skills", "Philippine History and Society", "Filipino"] },
          { icon: '<span class="iconify" data-icon="iconsax:content-cut" data-inline="false"></span>', label: "Your TechPro Electives", title: "What You'll Learn in This Cluster", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "Electives include Aesthetic Services (Beauty Care), Hairdressing, Caregiving (Adult Care), and Caregiving (Child Care). These are completely hands-on subjects that prepare you for real care and wellness industry work.", tags: ["Aesthetic Services and Beauty Care", "Hairdressing", "Caregiving (Adult Care)", "Caregiving (Child Care)"] },
          { icon: '<span class="iconify" data-icon="iconsax:target" data-inline="false"></span>', label: "Skills You Will Develop", title: "What This Cluster Builds in You", accent: "#0052cc", bg: "rgba(0, 82, 204, 0.12)", body: "You'll develop professional beauty and grooming skills, learn how to properly care for children and elderly adults, understand health and safety protocols, and build genuine empathy and patience.", tags: ["Beauty and Grooming", "Hair Care", "Adult Caregiving", "Child Care", "Health and Safety", "Empathy and Patience"] },
          { icon: '<span class="iconify" data-icon="iconsax:medal" data-inline="false"></span>', label: "National Certification (TESDA)", title: "You Can Earn a Cert While Still in SHS", accent: "#FFC72C", bg: "rgba(255, 199, 44, 0.12)", body: "You can earn a TESDA NC II in Beauty Care, Hairdressing, or Caregiving — certifications that qualify you to work professionally right after Senior High School, or even abroad.", tags: ["TESDA NC II", "Beauty Care Certification", "Hairdressing NC", "Caregiving Certification", "Overseas Opportunities"] },
          { icon: '<span class="iconify" data-icon="iconsax:rocket" data-inline="false"></span>', label: "Career Possibilities", title: "Jobs You Can Work Toward", accent: "#003087", bg: "rgba(0, 48, 135, 0.12)", body: "Graduates can work as Professional Caregivers, Beauty Therapists, Hairdressers, Salon Owners, or pursue college courses like BS Nursing, BS Psychology, or BS Early Childhood Education.", tags: ["Professional Caregiver", "Beauty Therapist", "Hairdresser", "Salon Owner", "BS Nursing", "BS Early Childhood Education"] }
        ]
      }
    ]
  }
];
